"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

def follows_rule(a, b, c, x):
    """Returns whether x follows the rules of the quadratic equation determined
       by a, b, and c."""
    a = float(a)
    b = float(b)
    c = float(c)
    x = float(x)
    return (-b + ((b**2.0) - (4.0 * a * c * x))**0.5) % (2.0 * a) == 0

def is_triangle(n):
    return follows_rule(1, 1, -2, n)

def is_pentagonal(n): # quadratic formula (only positive checks)
    return follows_rule(3, -1, -2, n)

def is_hexagonal(n):
    return follows_rule(2, -1, -1, n)

def trianglize(n):
    return (n * (n + 1)) / 2

n = 286
tn = trianglize(n)
while not is_hexagonal(tn) or not is_pentagonal(tn):
    n += 1
    tn = trianglize(n)
print n
print trianglize(n)
