"""Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?"""

def pentagonize(n):
    return n * ((3 * n) - 1) / 2

def is_pentagonal(n): # quadratic formula (only positive checks)
    return (1.0 + (1.0 - (4.0 * 3.0 * -2.0 * float(n)))**0.5) % -6 == 0

def diff_compare(p1, p2):
    if is_pentagonal(pentagonize(p1) + pentagonize(p2)):
        if is_pentagonal(abs(pentagonize(p1) - pentagonize(p2))):
            return True
    return False

p1 = 1
p2 = 1


while diff_compare(p1, p2) == False:
    current_diff = abs(pentagonize(p1) - pentagonize(p2))
    if (abs(current_diff - abs(pentagonize(p1) - pentagonize(p2+1))) >
        abs(current_diff - abs(pentagonize(p1+1) - pentagonize(p2)))):
        p1 += 1
        p2 = 1
    else:
        p2 += 1

print abs(pentagonize(p1) - pentagonize(p2))


